GET http://localhost:8383/

### TEST GET DASHBOARD
GET http://localhost:8383/dashboard

### TEST GET DATA ENDPOINT
GET http://localhost:8383/api/data

### TEST POST DATA ENDPOINT
POST http://localhost:8383/api/data
Content-Type: application/json

{
   "name": "Temttee"
}'


### TEST DELETE DATA ENDPOINT
DELETE http://localhost:8383/api/data